name = "AtBackslash"
uuid = "04ea9a2a-9613-4550-8ec7-b0cad5b6b706"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.1-DEV"

[compat]
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Test"]
